---
title: Akhmadkresna.Github.Io
timezone: UTC
collections:
  my_tags:
    title: My Tags
    output: true
    permalink: "/tag/:slug/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: my_tags
  values:
    layout: articles_by_tag
name: Notes
paginate: 25
url: https://akhmadkresna.github.io
blog_theme: light
about_enabled: false
discus_identifier: akhmadkresna
ga_analytics: 
local_fonts: false
rss_enabled: true
scrollappear_enabled: true
social:
  dribbble: 
  facebook: 
  flickr: 
  github: 
  linkedin: 
  twitter: 
  email: 
  bitcoin: 
  ethereum: 
  gitlab: 
  youtube: 
  twitch: 
  discord: 
  tumblr: 
  bitbucket: 
  docker: 
  instagram: 
  keybase: 
  medium: 
  spotify: 
  stackoverflow: 
  steam: 
assets:
  features:
    automatic_img_size: false
  sources:
  - _assets/fonts
  - _assets/icons
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets
  - _assets/yarn
exclude:
- ".travis.yml"
- bin/*
- circle.yml
- Gemfile
- Gemfile.lock
- package.json
- README.md
- vendor/
- yarn.lock
plugins:
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
- jemoji
paginate_path: "/posts/page/:num/"
permalink: posts/:slug
